### ISSUE TITLE
typo in base.py

### ISSUE THREAD

**Issue by Guest007** [olucurious/PyFCM#151] opened 2017-08-16 11:49 UTC
response_dict['multicast_id'].append(multicast_id) but must be 'multicast_ids' as response_dict key

**Comment by olucurious** [comment] 2017-08-16 15:36
Wow, thanks a lot for pointing that out

**Comment by olucurious** [comment] 2017-08-16 15:39
Fixed in the new 1.4.2 release

**Closed by olucurious** 2017-08-16 15:39 UTC

**Comment by Guest007** [comment] 2017-08-16 15:47
Glad to help ;-)

**Comment by arvindnrbt** [comment] 2018-03-29 09:54
Please update the releases page. I spent almost an hour wondering what went wrong when I got an exception stating just `multicast_id`. The current stable release 1.4.0 has this problem.

**Comment by olucurious** [comment] 2018-03-29 12:08
@arvindnrbt can you provide more details by posting the exception here?

**Comment by arvindnrbt** [comment] 2018-04-02 06:58
The exception just says `multicast_id`. This is because of the typo in `v1.4.0`. The problem is solved in the newer versions.
